spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# Ensure data.sql runs after Hibernate schema update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Admin Configuration
campusnote.admin.email=${ADMIN_EMAIL}
campusnote.admin.password=${ADMIN_PASSWORD}
